apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chaimeleon-operator.fullname" . }}
  labels:
    {{- include "chaimeleon-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chaimeleon-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chaimeleon-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chaimeleon-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
            - name: KEYCLOAK_CLIENT
              value: "{{ .Values.operatorConfiguration.keycloakClient }}"
            - name: KEYCLOAK_CLIENT_SECRET
              value: "{{ .Values.operatorConfiguration.keycloakClientSecret }}"
            - name: KEYCLOAK_ENDPOINT
              value: "{{ .Values.operatorConfiguration.keycloakEndpoint }}"
            - name: KEYCLOAK_REALM
              value: "{{ .Values.operatorConfiguration.keycloakRealm }}"
            - name: DATASET_SERVICE_ENDPOINT
              value: "{{ .Values.operatorConfiguration.datasetServiceEndpoint }}"
            - name: K8S_USER_PREFIX
              value: {{- include "chaimeleon-operator.k8sUserPrefix" . }}
            - name: OPERATOR_SERVICE_ACCOUNT_NAME
              value: {{ include "chaimeleon-operator.serviceAccountName" . }}
            - name: OPERATOR_SERVICE_ACCOUNT_NAMESPACE
              value: {{ .Release.Namespace }}      
          ports:
            - name: https
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: https
          readinessProbe:
            httpGet:
              path: /
              port: https
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

