apiVersion: v1
kind: Service
metadata:
  name: chaimeleon-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chaimeleon-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: https
  selector:
    {{- include "chaimeleon-operator.selectorLabels" . | nindent 4 }}
