apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "chaimeleon-operator.roleName" . }}
rules:

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: ["*"]
    resources: ["jobs", "deployments", "deployments/status" ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

